---
user: astralfrontier
group: astralfrontier
chdir: /var/www/astralfrontier.org/current
daemonize: true
environment: production
log: log/thin.log
max_conns: 1024
max_persistent_conns: 100
no-epoll: true
pid: tmp/pids/thin.pid
require: []
servers: 3
socket: /tmp/astralfrontier.org.sock
tag: astralfrontier.org
timeout: 30
wait: 30
