language: node_js
node_js:
- '8'
install:
  - npm install -g travis-ci-cloudfront-invalidation
  - yarn install
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_ID
  bucket: astralfrontier.org
  local-dir: public
  acl: public_read
  cache_control: "max-age=3600"
  skip_cleanup: true
  on:
    repo: astralfrontier/astralfrontier.org
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY -s $AWS_SECRET_ACCESS_ID -c $CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
notifications:
  slack:
    rooms:
      secure: KiP/TW95yHTg8QKvV3IQd7/lA2ppwaWgGvbd1VKZNo0PDQ73QeomJhsBv2GLVON9iUAWNoG54QfSnn4MhNKHdmorLMevumWg9P7i88R6sDjCJIAuLETvJqPLKLJu/txxuC8XopQ2ThKzDm27NKY+ySYpQdLyTyXqbAEojrdFETM=
