language: node_js
node_js:
- '8'
cache: pip
install:
  - pip install awscli
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: astralfrontier.org
  local-dir: public
  acl: public_read
  cache_control: "max-age=604800"
  skip_cleanup: true
  on:
    repo: astralfrontier/astralfrontier.org
after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
notifications:
  slack:
    rooms:
      secure: KiP/TW95yHTg8QKvV3IQd7/lA2ppwaWgGvbd1VKZNo0PDQ73QeomJhsBv2GLVON9iUAWNoG54QfSnn4MhNKHdmorLMevumWg9P7i88R6sDjCJIAuLETvJqPLKLJu/txxuC8XopQ2ThKzDm27NKY+ySYpQdLyTyXqbAEojrdFETM=
