language: node_js
node_js:
- '6'
deploy:
  provider: s3
  access_key_id: AKIAJRUAFJDMBFPNZRNQ
  secret_access_key:
    secure: RJF7/myIVf9rGk62cckN23NOl9MsjGDd8PdWT0LYKygQXwE//OLE5RaOxtBkGiHjJA2Qj43KHUchnQCwpWH2Q84EmkclRzgg72mISkKC2KdZiRyQ/hKX2FrWlMwHncPIcYkhrTSkhVN8YRptdWoKSUY4ypIzfatyuzQhcgh46S0=
  bucket: astralfrontier.org
  local-dir: build
  on:
    repo: astralfrontier/astralfrontier.org
notifications:
  slack:
    rooms:
      secure: KiP/TW95yHTg8QKvV3IQd7/lA2ppwaWgGvbd1VKZNo0PDQ73QeomJhsBv2GLVON9iUAWNoG54QfSnn4MhNKHdmorLMevumWg9P7i88R6sDjCJIAuLETvJqPLKLJu/txxuC8XopQ2ThKzDm27NKY+ySYpQdLyTyXqbAEojrdFETM=
